apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cluster.admin.name }}
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.cluster.admin.name }}
  namespace: kube-system
  annotations:
    meta.helm.sh/release-namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.cluster.admin.name }}
subjects:
  - kind: ServiceAccount
    name: health-admin
    namespace: kube-system